### ISSUE TITLE
Spring security role 체계화 필요

### ISSUE THREAD

**Issue by agape1225** [likelionknu/apply-page-backend#14]
Role 종류의 체계화가 필요할 듯...
Role의 인증 권한과 접근성 여부 설정 필요

Notion에 개발 문서를 만들어야할듯...

**Comment by klmhyeonwoo** [comment]
그렇군요,, 고민을 하는 과정,, 정말 멋있습니다,,

**Comment by agape1225** [comment]
Notion 역할 별 기능 정리로 만듬

근데 뭔가가 어려워보임...

Spring Security Configuration으로 Filter 처리를 하고 싶은데 들어오는 값마다 다르기에 코드로 설정해야할 것 같음.
