### ISSUE TITLE
/changeSendMail API 405 에러

### ISSUE THREAD

**Issue by klmhyeonwoo** [likelionknu/apply-page-backend#6]
###### `201704027`을 했을 때는 잘 먹음, 다른 학번으로 접근했을 때 405 에러가 발생

**Comment by agape1225** [comment]
프론트에서 아무 값을 주지 않고 NULL값을 주면 데이터베이스에 false가 아닌 NULL값이 저장됩니다.
그렇기 때문에 NULL Exception이 발생, 내부적으로 반전 연산자를 사용했기에, 에러가 발생했습니다.

프론트에서 아무값도 주지 않거나 false값을 줘야할듯합니다.
